#!/bin/bash
# 预构建信息脚本

echo "=== 屏幕监控系统 MySQL 预构建信息 ==="
echo "构建日期: $(date)"
echo "MySQL版本: $(mysql --version)"
echo ""
echo "包含的数据库结构:"
echo "📊 生产数据库: screen_monitoring"
echo "🔧 开发数据库: screen_monitoring_dev"
echo ""
echo "核心表结构:"
echo "  1. client_groups      - 客户端分组管理"
echo "  2. clients           - 客户端信息和状态"  
echo "  3. security_screenshots - 安全告警记录"
echo "  4. blockchain_whitelist - 地址白名单"
echo "  5. system_users      - 用户权限管理"
echo "  6. system_logs       - 操作日志审计"
echo "  7. client_online_logs - 在线时长记录"
echo ""
echo "高级功能:"
echo "  ⚙️ 存储过程: 数据清理和维护"
echo "  📊 视图: 实时统计和监控"
echo "  🔧 触发器: 自动数据处理"
echo "  🔍 函数: 智能检查和验证"
echo ""
echo "预设用户账户:"
echo "  👤 管理员: admin (密码: admin123)"
echo "  👤 操作员: operator (密码: operator123)" 
echo "  👤 查看员: viewer (密码: viewer123)"
echo "  👤 开发账户: dev_admin (密码: dev123)"
echo ""
echo "========================================="